### PR TITLE
Add Nix support and display a table

### PR DESCRIPTION
**Pull request by domenkozar**
Not ideal, but best I could do in 2h :)

How it looks now: http://imgur.com/srieZdZ

### CODE REVIEW

**Comment by madjar** [comment]
I have no idea whether the code is good or not, so there's no reason not to merge it. Also, I'll trust you blindly and not even try it locally, so the heroku hook will tell us if it's good.

I'm kind of sad there's no big glowing "42 days go" any more, but _osef_ (who cares), as we say here.

**Comment by domenkozar** [comment]
I'd add different colored labels to bold outdated channels

**Comment by domenkozar** [comment]
In another PR ;)

**Comment by madjar** [comment]
Awesome :)

**Comment by madjar** [comment]
Mmmm. I forgot to press the merge button the first time, didn't I?

**Pull request merged**
